---
# Ubuntu-18 setup
#

# http://coreemu.github.io/core/install.html#ubuntu--1804
#

- name: Install dependencies
  become: yes
  apt:
    pkg:
      - git
      - python-pip
      - python3-pip
      - automake
      - pkg-config 
      - gcc 
      - libev-dev 
      - bridge-utils 
      - ebtables 
      - python-dev 
      - python3-dev 
      - python-setuptools 
      - python3-setuptools 
      - tk 
      - libtk-img
      - python-sphinx
      - python3-sphinx
      - ruby 
      - ruby-dev 
      - rubygems 
      - build-essential
      - rpm
    state: present
    update_cache: yes
  tags: [package]

- name: Pip install grpcIO
  become: yes 
  pip:
    name: ['grpcio-tools','sphinx_rtd_theme', 'lxml', 'future']
    executable: pip3

- name: ensure core install path exists
  become: yes
  file:
    path: "{{core_build_dir}}"
    state: directory
    owner: "{{ansible_user_id}}"
  tags: [package]

- name: clone CORE
  git:
    repo: "{{ core_repo_url }}"
    dest: "{{ core_build_dir }}"
    version: "{{ core_git_version }}"
  tags: [package]

- name: ensure core fpm output path exist
  become: yes
  file:
    path: "/tmp/core-build"
    state: directory
    owner: "{{ansible_user_id}}"
  tags: [package]

- name: set env where core dumps eggs
  become: yes
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_env }}"

- name: build CORE 
  become: no
  #shell: ./bootstrap.sh && PYTHON=python3.6 ./configure && make && sudo make install && make doc && make fpm DESTDIR=/tmp/core-build
  shell: ./bootstrap.sh && PYTHON=python3.6 ./configure && make && sudo make install 
  args:
    chdir: "{{core_build_dir}}"
    creates: "{{core_build_dir}}/core-python-{{core_release_version}}.tgz"
  environment:
    PYTHONPATH: /usr/local/lib/python3.6/site-packages

